oauth:
  client:
    name: myappname123
    secret: myappsecret123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: MY-JWT-SECRET

management:
  endpoints:
    web:
      exposure:
        include: "*"
